octopus:
  environments:
    - development
    - production
  development:
    shard_one:
      host: localhost
      adapter: sqlite3
      database: db/development.sqlite3
  production:
    shard_one:
      host: localhost
      adapter: sqlite3
      database: db/development.sqlite3
